# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XUoE1VyORwUM9gxKsAmuS7F9wV-UuvDk
"""

#pip install streamlit

import streamlit as st
import requests
st.title("Analyse de sentiment des tweets")

# Ajoutez un champ de saisie pour le texte du tweet
tweet_text = st.text_area("Saisissez le texte du tweet :")

# Ajoutez un bouton pour soumettre le tweet
if st.button("Analyser"):
    # Effectuez une requête à votre API Flask sur Azure
    api_url = "URL_DE_VOTRE_API_SUR_AZURE"  # Remplacez par l'URL réelle
    response = requests.post(api_url, json={"text": tweet_text})

    # Affichez le sentiment associé
    if response.status_code == 200:
        sentiment = response.json()["sentiment"]
        st.write(f"Sentiment : {sentiment}")
    else:
        st.write("Erreur lors de l'analyse du tweet.")

